// world_capitals.js
// Liste der Länder mit Hauptstadt und Länder-Emoji (ISO-Flaggen als Emoji)
// Quelle: manuelle Zusammenstellung (faktische Daten)

const worldCapitals = [
  { country: 'Afghanistan', emoji: '🇦🇫', capital: 'Kabul' },
  { country: 'Albanien', emoji: '🇦🇱', capital: 'Tirana' },
  { country: 'Algerien', emoji: '🇩🇿', capital: 'Algier' },
  { country: 'Andorra', emoji: '🇦🇩', capital: 'Andorra la Vella' },
  { country: 'Angola', emoji: '🇦🇴', capital: 'Luanda' },
  { country: 'Antigua und Barbuda', emoji: '🇦🇬', capital: "St. John's" },
  { country: 'Argentinien', emoji: '🇦🇷', capital: 'Buenos Aires' },
  { country: 'Armenien', emoji: '🇦🇲', capital: 'Jerewan' },
  { country: 'Australien', emoji: '🇦🇺', capital: 'Canberra' },
  { country: 'Österreich', emoji: '🇦🇹', capital: 'Wien' },
  { country: 'Aserbaidschan', emoji: '🇦🇿', capital: 'Baku' },
  { country: 'Bahamas', emoji: '🇧🇸', capital: 'Nassau' },
  { country: 'Bahrain', emoji: '🇧🇭', capital: 'Manama' },
  { country: 'Bangladesch', emoji: '🇧🇩', capital: 'Dhaka' },
  { country: 'Barbados', emoji: '🇧🇧', capital: 'Bridgetown' },
  { country: 'Weißrussland', emoji: '🇧🇾', capital: 'Minsk' },
  { country: 'Belgien', emoji: '🇧🇪', capital: 'Brüssel' },
  { country: 'Belize', emoji: '🇧🇿', capital: 'Belmopan' },
  { country: 'Benin', emoji: '🇧🇯', capital: 'Porto-Novo' },
  { country: 'Bhutan', emoji: '🇧🇹', capital: 'Thimphu' },
  { country: 'Bolivien', emoji: '🇧🇴', capital: 'Sucre' },
  { country: 'Bosnien und Herzegowina', emoji: '🇧🇦', capital: 'Sarajevo' },
  { country: 'Botswana', emoji: '🇧🇼', capital: 'Gaborone' },
  { country: 'Brasilien', emoji: '🇧🇷', capital: 'Brasília' },
  { country: 'Brunei', emoji: '🇧🇳', capital: 'Bandar Seri Begawan' },
  { country: 'Bulgarien', emoji: '🇧🇬', capital: 'Sofia' },
  { country: 'Burkina Faso', emoji: '🇧🇫', capital: 'Ouagadougou' },
  { country: 'Burundi', emoji: '🇧🇮', capital: 'Gitega' },
  { country: 'Kambodscha', emoji: '🇰🇭', capital: 'Phnom Penh' },
  { country: 'Kamerun', emoji: '🇨🇲', capital: 'Yaoundé' },
  { country: 'Kanada', emoji: '🇨🇦', capital: 'Ottawa' },
  { country: 'Kap Verde', emoji: '🇨🇻', capital: 'Praia' },
  { country: 'Zentralafrikanische Republik', emoji: '🇨🇫', capital: 'Bangui' },
  { country: 'Tschad', emoji: '🇹🇩', capital: 'N'Djamena' },
  { country: 'Chile', emoji: '🇨🇱', capital: 'Santiago' },
  { country: 'China', emoji: '🇨🇳', capital: 'Peking' },
  { country: 'Kolumbien', emoji: '🇨🇴', capital: 'Bogotá' },
  { country: 'Komoren', emoji: '🇰🇲', capital: 'Moroni' },
  { country: 'Kongo (Republik)', emoji: '🇨🇬', capital: 'Brazzaville' },
  { country: 'Kongo (DRC)', emoji: '🇨🇩', capital: 'Kinshasa' },
  { country: 'Costa Rica', emoji: '🇨🇷', capital: 'San José' },
  { country: 'Kroatien', emoji: '🇭🇷', capital: 'Zagreb' },
  { country: 'Kuba', emoji: '🇨🇺', capital: 'Havanna' },
  { country: 'Zypern', emoji: '🇨🇾', capital: 'Nikosia' },
  { country: 'Tschechien', emoji: '🇨🇿', capital: 'Prag' },
  { country: 'Dänemark', emoji: '🇩🇰', capital: 'Kopenhagen' },
  { country: 'Dschibuti', emoji: '🇩🇯', capital: 'Dschibuti' },
  { country: 'Dominica', emoji: '🇩🇲', capital: 'Roseau' },
  { country: 'Dominikanische Republik', emoji: '🇩🇴', capital: 'Santo Domingo' },
  { country: 'Ecuador', emoji: '🇪🇨', capital: 'Quito' },
  { country: 'Ägypten', emoji: '🇪🇬', capital: 'Kairo' },
  { country: 'El Salvador', emoji: '🇸🇻', capital: 'San Salvador' },
  { country: 'Äquatorialguinea', emoji: '🇬🇶', capital: 'Malabo' },
  { country: 'Eritrea', emoji: '🇪🇷', capital: 'Asmara' },
  { country: 'Estland', emoji: '🇪🇪', capital: 'Tallinn' },
  { country: 'Eswatini', emoji: '🇸🇿', capital: 'Mbabane' },
  { country: 'Äthiopien', emoji: '🇪🇹', capital: 'Addis Abeba' },
  { country: 'Fidschi', emoji: '🇫🇯', capital: 'Suva' },
  { country: 'Finnland', emoji: '🇫🇮', capital: 'Helsinki' },
  { country: 'Frankreich', emoji: '🇫🇷', capital: 'Paris' },
  { country: 'Gabon', emoji: '🇬🇦', capital: 'Libreville' },
  { country: 'Gambia', emoji: '🇬🇲', capital: 'Banjul' },
  { country: 'Georgien', emoji: '🇬🇪', capital: 'Tiflis' },
  { country: 'Deutschland', emoji: '🇩🇪', capital: 'Berlin' },
  { country: 'Ghana', emoji: '🇬🇭', capital: 'Accra' },
  { country: 'Griechenland', emoji: '🇬🇷', capital: 'Athen' },
  { country: 'Grenada', emoji: '🇬🇩', capital: 'Saint George's' },
  { country: 'Guatemala', emoji: '🇬🇹', capital: 'Guatemala-Stadt' },
  { country: 'Guinea', emoji: '🇬🇳', capital: 'Conakry' },
  { country: 'Guinea-Bissau', emoji: '🇬🇼', capital: 'Bissau' },
  { country: 'Guyana', emoji: '🇬🇾', capital: 'Georgetown' },
  { country: 'Haiti', emoji: '🇭🇹', capital: 'Port-au-Prince' },
  { country: 'Honduras', emoji: '🇭🇳', capital: 'Tegucigalpa' },
  { country: 'Ungarn', emoji: '🇭🇺', capital: 'Budapest' },
  { country: 'Island', emoji: '🇮🇸', capital: 'Reykjavík' },
  { country: 'Indien', emoji: '🇮🇳', capital: 'Neu-Delhi' },
  { country: 'Indonesien', emoji: '🇮🇩', capital: 'Jakarta' },
  { country: 'Iran', emoji: '🇮🇷', capital: 'Teheran' },
  { country: 'Irak', emoji: '🇮🇶', capital: 'Bagdad' },
  { country: 'Irland', emoji: '🇮🇪', capital: 'Dublin' },
  { country: 'Israel', emoji: '🇮🇱', capital: 'Jerusalem' },
  { country: 'Italien', emoji: '🇮🇹', capital: 'Rom' },
  { country: 'Jamaika', emoji: '🇯🇲', capital: 'Kingston' },
  { country: 'Japan', emoji: '🇯🇵', capital: 'Tokio' },
  { country: 'Jordanien', emoji: '🇯🇴', capital: 'Amman' },
  { country: 'Kasachstan', emoji: '🇰🇿', capital: 'Astana' },
  { country: 'Kenia', emoji: '🇰🇪', capital: 'Nairobi' },
  { country: 'Kiribati', emoji: '🇰🇮', capital: 'South Tarawa' },
  { country: 'Nordkorea', emoji: '🇰🇵', capital: 'Pjöngjang' },
  { country: 'Südkorea', emoji: '🇰🇷', capital: 'Seoul' },
  { country: 'Kuwait', emoji: '🇰🇼', capital: 'Kuwait-Stadt' },
  { country: 'Kirgisistan', emoji: '🇰🇬', capital: 'Bischkek' },
  { country: 'Laos', emoji: '🇱🇦', capital: 'Vientiane' },
  { country: 'Lettland', emoji: '🇱🇻', capital: 'Riga' },
  { country: 'Libanon', emoji: '🇱🇧', capital: 'Beirut' },
  { country: 'Lesotho', emoji: '🇱🇸', capital: 'Maseru' },
  { country: 'Liberia', emoji: '🇱🇷', capital: 'Monrovia' },
  { country: 'Libyen', emoji: '🇱🇾', capital: 'Tripolis' },
  { country: 'Liechtenstein', emoji: '🇱🇮', capital: 'Vaduz' },
  { country: 'Litauen', emoji: '🇱🇹', capital: 'Vilnius' },
  { country: 'Luxemburg', emoji: '🇱🇺', capital: 'Luxemburg' },
  { country: 'Madagaskar', emoji: '🇲🇬', capital: 'Antananarivo' },
  { country: 'Malawi', emoji: '🇲🇼', capital: 'Lilongwe' },
  { country: 'Malaysia', emoji: '🇲🇾', capital: 'Kuala Lumpur' },
  { country: 'Malediven', emoji: '🇲🇻', capital: 'Malé' },
  { country: 'Mali', emoji: '🇲🇱', capital: 'Bamako' },
  { country: 'Malta', emoji: '🇲🇹', capital: 'Valletta' },
  { country: 'Marshallinseln', emoji: '🇲🇭', capital: 'Majuro' },
  { country: 'Mauretanien', emoji: '🇲🇷', capital: 'Nouakchott' },
  { country: 'Mauritius', emoji: '🇲🇺', capital: 'Port Louis' },
  { country: 'Mexiko', emoji: '🇲🇽', capital: 'Mexiko-Stadt' },
  { country: 'Mikronesien', emoji: '🇫🇲', capital: 'Palikir' },
  { country: 'Moldau', emoji: '🇲🇩', capital: 'Chișinău' },
  { country: 'Monaco', emoji: '🇲🇨', capital: 'Monaco' },
  { country: 'Mongolei', emoji: '🇲🇳', capital: 'Ulaanbaatar' },
  { country: 'Montenegro', emoji: '🇲🇪', capital: 'Podgorica' },
  { country: 'Marokko', emoji: '🇲🇦', capital: 'Rabat' },
  { country: 'Mosambik', emoji: '🇲🇿', capital: 'Maputo' },
  { country: 'Myanmar', emoji: '🇲🇲', capital: 'Naypyidaw' },
  { country: 'Namibia', emoji: '🇳🇦', capital: 'Windhoek' },
  { country: 'Nauru', emoji: '🇳🇷', capital: 'Yaren (De-facto)' },
  { country: 'Nepal', emoji: '🇳🇵', capital: 'Kathmandu' },
  { country: 'Niederlande', emoji: '🇳🇱', capital: 'Amsterdam' },
  { country: 'Neuseeland', emoji: '🇳🇿', capital: 'Wellington' },
  { country: 'Nikaragua', emoji: '🇳🇮', capital: 'Managua' },
  { country: 'Niger', emoji: '🇳🇪', capital: 'Niamey' },
  { country: 'Nigeria', emoji: '🇳🇬', capital: 'Abuja' },
  { country: 'Nordmazedonien', emoji: '🇲🇰', capital: 'Skopje' },
  { country: 'Norwegen', emoji: '🇳🇴', capital: 'Oslo' },
  { country: 'Oman', emoji: '🇴🇲', capital: 'Maskat' },
  { country: 'Pakistan', emoji: '🇵🇰', capital: 'Islamabad' },
  { country: 'Palau', emoji: '🇵🇼', capital: 'Ngerulmud' },
  { country: 'Panama', emoji: '🇵🇦', capital: 'Panama-Stadt' },
  { country: 'Papua-Neuguinea', emoji: '🇵🇬', capital: 'Port Moresby' },
  { country: 'Paraguay', emoji: '🇵🇾', capital: 'Asunción' },
  { country: 'Peru', emoji: '🇵🇪', capital: 'Lima' },
  { country: 'Philippinen', emoji: '🇵🇭', capital: 'Manila' },
  { country: 'Polen', emoji: '🇵🇱', capital: 'Warschau' },
  { country: 'Portugal', emoji: '🇵🇹', capital: 'Lissabon' },
  { country: 'Katar', emoji: '🇶🇦', capital: 'Doha' },
  { country: 'Rumänien', emoji: '🇷🇴', capital: 'Bukarest' },
  { country: 'Russland', emoji: '🇷🇺', capital: 'Moskau' },
  { country: 'Ruanda', emoji: '🇷🇼', capital: 'Kigali' },
  { country: 'St. Kitts und Nevis', emoji: '🇰🇳', capital: 'Basseterre' },
  { country: 'St. Lucia', emoji: '🇱🇨', capital: 'Castries' },
  { country: 'St. Vincent und die Grenadinen', emoji: '🇻🇨', capital: 'Kingstown' },
  { country: 'Samoa', emoji: '🇼🇸', capital: 'Apia' },
  { country: 'San Marino', emoji: '🇸🇲', capital: 'San Marino' },
  { country: 'São Tomé und Príncipe', emoji: '🇸🇹', capital: 'São Tomé' },
  { country: 'Saudi-Arabien', emoji: '🇸🇦', capital: 'Riad' },
  { country: 'Senegal', emoji: '🇸🇳', capital: 'Dakar' },
  { country: 'Serbien', emoji: '🇷🇸', capital: 'Belgrad' },
  { country: 'Seychellen', emoji: '🇸🇨', capital: 'Victoria' },
  { country: 'Sierra Leone', emoji: '🇸🇱', capital: 'Freetown' },
  { country: 'Singapur', emoji: '🇸🇬', capital: 'Singapur' },
  { country: 'Slowakei', emoji: '🇸🇰', capital: 'Bratislava' },
  { country: 'Slowenien', emoji: '🇸🇮', capital: 'Ljubljana' },
  { country: 'Salomonen', emoji: '🇸🇧', capital: 'Honiara' },
  { country: 'Somalia', emoji: '🇸🇴', capital: 'Mogadischu' },
  { country: 'Südafrika', emoji: '🇿🇦', capital: 'Pretoria (administrativ), Kapstadt (legislativ)' },
  { country: 'Südsudan', emoji: '🇸🇸', capital: 'Juba' },
  { country: 'Spanien', emoji: '🇪🇸', capital: 'Madrid' },
  { country: 'Sri Lanka', emoji: '🇱🇰', capital: 'Sri Jayawardenepura Kotte' },
  { country: 'Sudan', emoji: '🇸🇩', capital: 'Khartum' },
  { country: 'Suriname', emoji: '🇸🇷', capital: 'Paramaribo' },
  { country: 'Schweden', emoji: '🇸🇪', capital: 'Stockholm' },
  { country: 'Schweiz', emoji: '🇨🇭', capital: 'Bern' },
  { country: 'Syrien', emoji: '🇸🇾', capital: 'Damaskus' },
  { country: 'Taiwan', emoji: '🇹🇼', capital: 'Taipeh' },
  { country: 'Tadschikistan', emoji: '🇹🇯', capital: 'Duschanbe' },
  { country: 'Tansania', emoji: '🇹🇿', capital: 'Dodoma' },
  { country: 'Thailand', emoji: '🇹🇭', capital: 'Bangkok' },
  { country: 'Togo', emoji: '🇹🇬', capital: 'Lomé' },
  { country: 'Tonga', emoji: '🇹🇴', capital: "Nuku'alofa" },
  { country: 'Trinidad und Tobago', emoji: '🇹🇹', capital: 'Port of Spain' },
  { country: 'Tunesien', emoji: '🇹🇳', capital: 'Tunis' },
  { country: 'Türkei', emoji: '🇹🇷', capital: 'Ankara' },
  { country: 'Turkmenistan', emoji: '🇹🇲', capital: 'Aschgabat' },
  { country: 'Tuvalu', emoji: '🇹🇻', capital: 'Funafuti' },
  { country: 'Uganda', emoji: '🇺🇬', capital: 'Kampala' },
  { country: 'Ukraine', emoji: '🇺🇦', capital: 'Kyjiw' },
  { country: 'Vereinigte Arabische Emirate', emoji: '🇦🇪', capital: 'Abu Dhabi' },
  { country: 'Vereinigtes Königreich', emoji: '🇬🇧', capital: 'London' },
  { country: 'USA', emoji: '🇺🇸', capital: 'Washington, D.C.' },
  { country: 'Uruguay', emoji: '🇺🇾', capital: 'Montevideo' },
  { country: 'Usbekistan', emoji: '🇺🇿', capital: 'Taschkent' },
  { country: 'Vanuatu', emoji: '🇻🇺', capital: 'Port Vila' },
  { country: 'Vatikanstadt', emoji: '🇻🇦', capital: 'Vatikanstadt' },
  { country: 'Venezuela', emoji: '🇻🇪', capital: 'Caracas' },
  { country: 'Vietnam', emoji: '🇻🇳', capital: 'Hanoi' },
  { country: 'Jemen', emoji: '🇾🇪', capital: 'Sanaa' },
  { country: 'Sambia', emoji: '🇿🇲', capital: 'Lusaka' },
  { country: 'Simbabwe', emoji: '🇿🇼', capital: 'Harare' }
];

// Datei beenden; im Browser steht `worldCapitals` global zur Verfügung
